FROM node:0.10.38
MAINTAINER David JM <biodavidjm@gmail.com>

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y vim

# npm install --production
# export PATH="$(npm bin):$PATH" 
# bower install --allow-root --config.interactive=false





