FROM node:0.10.38
MAINTAINER David JM <biodavidjm@gmail.com>
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y vim
RUN apt-get install -y libpng-dev
# RUN npm install -g grunt-cli bower
